title: Sundarakalathi K # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Passionate Frontend Developer
  <br><br>
  <a href="mailto:sundarakalathi1311@gmail.com">sundarakalathi1311@gmail.com </a>
  <br><br>
  <a href="https://www.linkedin.com/in/sundarakalathi-k-992b011a1/">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/Sundarakalathi-K"><b>View My Github Profile</b></a> 
github:
  is_project_page: false
theme: jekyll-theme-minimal
<script src="http://code.jquery.com/jquery-1.4.2.min.js"></script> <script> var x = document.getElementsByClassName("site-footer-credits"); setTimeout(() => { x[0].remove(); }, 10); </script>
